# syntax=docker/dockerfile:1

FROM golang:1.20-alpine AS build

# Set destination for COPY
WORKDIR /sorter

# Download go modules
COPY go.mod ./
RUN go mod download

COPY ["*.go","*.html","./"]
RUN go build -o /main

FROM scratch

WORKDIR /

COPY --from=build ["*.go","*.html","/main/"]

EXPOSE 3000

ENTRYPOINT [ "/main" ]